//
//  RecentPostsModels.swift
//  SuperNewsSB
//
//  Created by Luis Zapata on 12-01-20.
//  Copyright (c) 2020 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostsModel {
    enum Recent {
        struct Request {}
        
        struct Response: Decodable {
            var hits: [Hit]?
            struct Hit: Decodable {
                var created_at_i: Double
                var author: String?
                var story_title: String?
                var story_url: String?
                var objectID: String
            }
        }
        
        struct ViewModel {
            struct DisplayedPost: Identifiable, Encodable, Decodable {
                var id: String
                var createdAt: Date
                var author: String?
                var storyTitle: String
                var storyUrl: String
            }
            var displayedPost: [DisplayedPost]
        }
    }

}
