//
//  RecentPostsPresenter.swift
//  SuperNewsSB
//
//  Created by Luis Zapata on 12-01-20.
//  Copyright (c) 2020 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecentPostsPresentationLogic
{
    func presentPosts(viewModel: [PostsModel.Recent.ViewModel.DisplayedPost])
}

class RecentPostsPresenter: RecentPostsPresentationLogic
{
  weak var viewController: RecentPostsDisplayLogic?

  func presentPosts(viewModel: [PostsModel.Recent.ViewModel.DisplayedPost])
  {
    viewController?.displayPosts(viewModel: viewModel)
    viewController?.endRefreshing()
  }
}
