//
//  RecentPostsRouter.swift
//  SuperNewsSB
//
//  Created by Luis Zapata on 12-01-20.
//  Copyright (c) 2020 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RecentPostsRoutingLogic
{
    func routeToPost(url: String)
}

protocol RecentPostsDataPassing
{
    var dataStore: RecentPostsDataStore? { get }
}

class RecentPostsRouter: NSObject, RecentPostsRoutingLogic, RecentPostsDataPassing
{
    weak var viewController: RecentPostsViewController?
    var dataStore: RecentPostsDataStore?
    
    // MARK: Routing
    
    func routeToPost(url: String)
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "PostViewController") as! PostViewController
        destinationVC.url = url
        //passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: RecentPostsViewController, destination: PostViewController)
    {
        source.show(destination, sender: nil)
    }
}
